// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWEkU3LqBQU9SCC9gDLg7UR7iN1aJF9mw',
    appId: '1:460444467643:web:6f685aad03abc1f173849e',
    messagingSenderId: '460444467643',
    projectId: 'chat-app-da8b4',
    authDomain: 'chat-app-da8b4.firebaseapp.com',
    storageBucket: 'chat-app-da8b4.appspot.com',
    measurementId: 'G-CXE4NFM6Y1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5SvOEj4WTDlOA_NpmrpCo3Q-z3aEbhVw',
    appId: '1:460444467643:android:c3bc29e107cc347b73849e',
    messagingSenderId: '460444467643',
    projectId: 'chat-app-da8b4',
    storageBucket: 'chat-app-da8b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV_f1eAw1xxALm7aD3JhQ2gYLaKTrRcAY',
    appId: '1:460444467643:ios:e4b652ee29cb5a3173849e',
    messagingSenderId: '460444467643',
    projectId: 'chat-app-da8b4',
    storageBucket: 'chat-app-da8b4.appspot.com',
    iosClientId: '460444467643-nj1f92q1nflngin15j9k66e9ppqag09f.apps.googleusercontent.com',
    iosBundleId: 'com.example.scholarChat',
  );
}
